# Introduction

Using this Python notebook you will:

1.  Understand three Chicago datasets
2.  Load the three datasets into three tables in a SQLIte database
3.  Execute SQL queries to answer assignment questions

# Import library & extension

In [1]:
import pandas as pd
import prettytable
import sqlite3
%load_ext sql
prettytable.DEFAULT = 'DEFAULT'

In [2]:
# establish a connection
conn = sqlite3.connect("FinalDB.db")
curr = conn.cursor()
print("Connection is created")

Connection is created

In [12]:
# connect to a SQLite database file
%sql sqlite:///FinalDB.db
print("Connected to the database file")

Connected to the database file

In [13]:
# create and load census_data to sql
census_data_df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01")
census_data_df.to_sql("census_data", conn, if_exists='replace', index=False, method='multi')

78

In [21]:
census_data_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 9 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   COMMUNITY_AREA_NUMBER                         77 non-null     float64
 1   COMMUNITY_AREA_NAME                           78 non-null     str
 2   PERCENT_OF_HOUSING_CROWDED                    78 non-null     float64
 3   PERCENT_HOUSEHOLDS_BELOW_POVERTY              78 non-null     float64
 4   PERCENT_AGED_16__UNEMPLOYED                   78 non-null     float64
 5   PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA  78 non-null     float64
 6   PERCENT_AGED_UNDER_18_OR_OVER_64              78 non-null     float64
 7   PER_CAPITA_INCOME                             78 non-null     int64
 8   HARDSHIP_INDEX                                77 non-null     float64
dtypes: float64(7), int64(1), str(1)
memory usage: 5.6 KB

In [8]:
chicago_public_schools_df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01")
chicago_public_schools_df.to_sql("chicago_public_schools_data", conn, if_exists='replace', index=False, method='multi', chunksize=12)

566

In [60]:
chicago_public_schools_df

,School_ID,NAME_OF_SCHOOL,"Elementary, Middle, or High School",Street_Address,City,State,ZIP_Code,Phone_Number,Link,Network_Manager,...,Freshman_on_Track_Rate__,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,Ward,Police_District,Location
0,610038,Abraham Lincoln Elementary School,ES,615 W Kemper Pl,Chicago,IL,60614,(773) 534-5720,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,NDA,1171699.458,1915829.428,41.924497,-87.644522,7,LINCOLN PARK,43,18,"(41.92449696, -87.64452163)"
1,610281,Adam Clayton Powell Paideia Community Academy ...,ES,7511 S South Shore Dr,Chicago,IL,60649,(773) 535-6650,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,NDA,1196129.985,1856209.466,41.760324,-87.556736,43,SOUTH SHORE,7,4,"(41.76032435, -87.55673627)"
2,610185,Adlai E Stevenson Elementary School,ES,8010 S Kostner Ave,Chicago,IL,60652,(773) 535-2280,http://schoolreports.cps.edu/SchoolProgressRep...,Midway Elementary Network,...,NDA,1148427.165,1851012.215,41.747111,-87.731702,70,ASHBURN,13,8,"(41.74711093, -87.73170248)"
3,609993,Agustin Lara Elementary Academy,ES,4619 S Wolcott Ave,Chicago,IL,60609,(773) 535-4389,http://schoolreports.cps.edu/SchoolProgressRep...,Pershing Elementary Network,...,NDA,1164504.290,1873959.199,41.809757,-87.672145,61,NEW CITY,20,9,"(41.8097569, -87.6721446)"
4,610513,Air Force Academy High School,HS,3630 S Wells St,Chicago,IL,60609,(773) 535-1590,http://schoolreports.cps.edu/SchoolProgressRep...,Southwest Side High School Network,...,91.8,1175177.622,1880745.126,41.828146,-87.632794,34,ARMOUR SQUARE,11,9,"(41.82814609, -87.63279369)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561,610172,William T Sherman Elementary School,ES,1000 W 52nd St,Chicago,IL,60609,(773) 535-1757,http://schoolreports.cps.edu/SchoolProgressRep...,AUSL Schools,...,NDA,1170500.817,1870373.159,41.799788,-87.650255,61,NEW CITY,16,9,"(41.79978772, -87.65025483)"
562,609844,William W Carter Elementary School,ES,5740 S Michigan Ave,Chicago,IL,60637,(773) 535-0860,http://schoolreports.cps.edu/SchoolProgressRep...,Burnham Park Elementary Network,...,NDA,1178101.365,1866810.123,41.789841,-87.622490,40,WASHINGTON PARK,20,2,"(41.78984129, -87.62248974)"
563,610088,Wolfgang A Mozart Elementary School,ES,2200 N Hamlin Ave,Chicago,IL,60647,(773) 534-4160,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,NDA,1150644.396,1914368.955,41.920927,-87.721925,22,LOGAN SQUARE,35,25,"(41.92092734, -87.72192541)"
564,609977,Woodlawn Community Elementary School,ES,6657 S Kimbark Ave,Chicago,IL,60637,(773) 535-0801,http://schoolreports.cps.edu/SchoolProgressRep...,Burnham Park Elementary Network,...,NDA,1185825.188,1860883.579,41.773400,-87.594356,42,WOODLAWN,5,3,"(41.77339962, -87.59435584)"
565,610392,World Language Academy High School,HS,3120 S Kostner Ave,Chicago,IL,60623,(773) 535-4334,http://schoolreports.cps.edu/SchoolProgressRep...,West Side High School Network,...,76,1147521.302,1883405.128,41.836020,-87.734195,30,SOUTH LAWNDALE,22,10,"(41.83601953, -87.73419465)"

In [9]:
chicago_crime_df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01")
chicago_crime_df.to_sql("chicago_crime_data", conn, if_exists='replace', index=False, method='multi')

533

In [61]:
chicago_crime_df

,ID,CASE_NUMBER,DATE,BLOCK,IUCR,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION,ARREST,DOMESTIC,...,DISTRICT,WARD,COMMUNITY_AREA_NUMBER,FBICODE,X_COORDINATE,Y_COORDINATE,YEAR,LATITUDE,LONGITUDE,LOCATION
0,3512276,HK587712,2004-08-28,047XX S KEDZIE AVE,890,THEFT,FROM BUILDING,SMALL RETAIL STORE,False,False,...,9,14.0,58.0,6,1155838.0,1873050.0,2004,41.807440,-87.703956,"(41.8074405, -87.703955849)"
1,3406613,HK456306,2004-06-26,009XX N CENTRAL PARK AVE,820,THEFT,$500 AND UNDER,OTHER,False,False,...,11,27.0,23.0,6,1152206.0,1906127.0,2004,41.898280,-87.716406,"(41.898279962, -87.716405505)"
2,8002131,HT233595,2011-04-04,043XX S WABASH AVE,820,THEFT,$500 AND UNDER,NURSING HOME/RETIREMENT HOME,False,False,...,2,3.0,38.0,6,1177436.0,1876313.0,2011,41.815933,-87.624642,"(41.815933131, -87.624642127)"
3,7903289,HT133522,2010-12-30,083XX S KINGSTON AVE,840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,4,7.0,46.0,6,1194622.0,1850125.0,2010,41.743665,-87.562463,"(41.743665322, -87.562462756)"
4,10402076,HZ138551,2016-02-02,033XX W 66TH ST,820,THEFT,$500 AND UNDER,ALLEY,False,False,...,8,15.0,66.0,6,1155240.0,1860661.0,2016,41.773455,-87.706480,"(41.773455295, -87.706480471)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,10453948,HZ192829,2016-03-01,028XX E 79TH ST,1055,HUMAN TRAFFICKING,INVOLUNTARY SERVITUDE,APARTMENT,False,False,...,4,7.0,46.0,26,1196679.0,1853139.0,2016,41.751885,-87.554826,"(41.751885152, -87.554825997)"
529,10397129,HZ133234,2016-01-29,006XX W HARRISON ST,5114,NON - CRIMINAL,FOID - REVOCATION,STREET,False,False,...,1,2.0,28.0,26,1172257.0,1897564.0,2016,41.874363,-87.643013,"(41.874363279, -87.643013039)"
530,3269495,HJ747227,2003-11-08,012XX W 81ST ST,510,RITUALISM,AGG RIT MUT: HANDS/FIST/FEET SERIOUS INJURY,OTHER,False,False,...,6,21.0,71.0,04B,1169648.0,1851076.0,2003,41.746852,-87.653941,"(41.746852486, -87.653941385)"
531,10840565,JA143710,2017-02-06,009XX N KARLOV AVE,5073,NON-CRIMINAL (SUBJECT SPECIFIED),NOTIFICATION OF CIVIL NO CONTACT ORDER,RESIDENCE,False,True,...,11,37.0,23.0,26,1148881.0,1905963.0,2017,41.897895,-87.728622,"(41.89789489, -87.728622316)"
532,1326195,G021609,2001-01-11,087XX S ESCANABA AV,9901,DOMESTIC VIOLENCE,DOMESTIC VIOLENCE,APARTMENT,True,True,...,4,NaN,NaN,08B,1196869.0,1847416.0,2001,41.736176,-87.554320,"(41.73617608, -87.554319607)"

In [14]:
# use this line to recheck table in database
%sql select name from sqlite_master where type='table';

 * sqlite:///FinalDB.db
   sqlite:///SQLiteMagic.db
Done.

[('chicago_public_schools_data',), ('chicago_crime_data',), ('census_data',)]

In [19]:
# total number of crimes recorded in the CRIME table
%sql select count(*) as total_number_of_crimes_rec from census_data

 * sqlite:///FinalDB.db
   sqlite:///SQLiteMagic.db
Done.

[(78,)]

In [23]:
# list community area names and numbers with per capita income less than 11000
%sql select community_area_name, per_capita_income \
     from census_data \
     where per_capita_income < 11000

 * sqlite:///FinalDB.db
   sqlite:///SQLiteMagic.db
Done.

[('West Garfield Park', 10934),
 ('South Lawndale', 10402),
 ('Fuller Park', 10432),
 ('Riverdale', 8201)]

In [25]:
# List all case numbers for crimes involving minors?(children are not considered minors for the purposes of crime analysis)
%sql select * from chicago_crime_data where description like '%minor%';

 * sqlite:///FinalDB.db
   sqlite:///SQLiteMagic.db
Done.

[(3987219, 'HL266884', '2005-03-31', '024XX N CLARK ST', '2210', 'LIQUOR LAW VIOLATION', 'SELL/GIVE/DEL LIQUOR TO MINOR', 'CONVENIENCE STORE', 1, 0, 2333, 19, 43.0, 7.0, '22', 1172680.0, 1916483.0, 2005, 41.92626872, -87.64089934, '(41.926268719, -87.640899336)'),
 (3266814, 'HK238408', '2004-03-13', '093XX S STONY ISLAND AVE', '2230', 'LIQUOR LAW VIOLATION', 'ILLEGAL CONSUMPTION BY MINOR', 'ALLEY', 1, 0, 413, 4, 8.0, 48.0, '22', 1188539.0, 1843379.0, 2004, 41.72530099, -87.58496589, '(41.72530099, -87.584965887)')]

In [27]:
# List all kidnapping crimes involving a child?
%sql select * from chicago_crime_data where description like '%child%' or primary_type like '%kidnapping%'

 * sqlite:///FinalDB.db
   sqlite:///SQLiteMagic.db
Done.

[(5766654, 'HN567387', '2007-09-02', '026XX W BELMONT AVE', '1754', 'OFFENSE INVOLVING CHILDREN', 'AGG SEX ASSLT OF CHILD FAM MBR', 'CHURCH/SYNAGOGUE/PLACE OF WORSHIP', 0, 0, 1411, 14, 1.0, 21.0, '2', 1158166.0, 1921161.0, 2007, 41.93941471, -87.69410322, '(41.939414712, -87.694103222)'),
 (6986273, 'HR391350', '2009-06-23', '015XX S KOLIN AVE', '1753', 'OFFENSE INVOLVING CHILDREN', 'SEX ASSLT OF CHILD BY FAM MBR', 'APARTMENT', 0, 1, 1012, 10, 24.0, 29.0, '2', 1147638.0, 1892092.0, 2009, 41.85985521, -87.73354382, '(41.859855212, -87.733543816)'),
 (5276766, 'HN144152', '2007-01-26', '050XX W VAN BUREN ST', '1792', 'KIDNAPPING', 'CHILD ABDUCTION/STRANGER', 'STREET', 0, 0, 1533, 15, 29.0, 25.0, '20', 1143050.0, 1897546.0, 2007, 41.87490841, -87.75024931, '(41.874908413, -87.750249307)')]

In [64]:
# List the kind of crimes that were recorded at schools. (No repetitions)
%sql select distinct(primary_type), location_description \
     from chicago_crime_data \
     where location_description like '%school%'

 * sqlite:///FinalDB.db
   sqlite:///SQLiteMagic.db
Done.

[('BATTERY', 'SCHOOL, PUBLIC, GROUNDS'),
 ('BATTERY', 'SCHOOL, PUBLIC, BUILDING'),
 ('CRIMINAL DAMAGE', 'SCHOOL, PUBLIC, GROUNDS'),
 ('NARCOTICS', 'SCHOOL, PUBLIC, GROUNDS'),
 ('NARCOTICS', 'SCHOOL, PUBLIC, BUILDING'),
 ('ASSAULT', 'SCHOOL, PUBLIC, GROUNDS'),
 ('CRIMINAL TRESPASS', 'SCHOOL, PUBLIC, GROUNDS'),
 ('PUBLIC PEACE VIOLATION', 'SCHOOL, PRIVATE, BUILDING'),
 ('PUBLIC PEACE VIOLATION', 'SCHOOL, PUBLIC, BUILDING')]

In [33]:
# List the type of schools along with the average safety score for each type.
%sql select "Elementary, Middle, or High School", avg(safety_score) \
     from chicago_public_schools_data \
     group by "Elementary, Middle, or High School"

 * sqlite:///FinalDB.db
   sqlite:///SQLiteMagic.db
Done.

[('ES', 49.52038369304557), ('HS', 49.62352941176471), ('MS', 48.0)]

In [34]:
# List 5 community areas with highest % of households below poverty line
%sql select community_area_name \
     from census_data \
     order by percent_households_below_poverty desc \
     limit 5

 * sqlite:///FinalDB.db
   sqlite:///SQLiteMagic.db
Done.

[('Riverdale',),
 ('Fuller Park',),
 ('Englewood',),
 ('North Lawndale',),
 ('East Garfield Park',)]

In [43]:
# Which community area is most crime prone? Display the coumminty area number only.
%sql select community_area_number, count(community_area_number) as freq \
     from chicago_crime_data \
     group by community_area_number \
     order by count(community_area_number) desc limit 5

 * sqlite:///FinalDB.db
   sqlite:///SQLiteMagic.db
Done.

[(25.0, 43), (23.0, 22), (68.0, 21), (29.0, 16), (28.0, 16)]

In [57]:
# Use a sub-query to find the name of the community area with highest hardship index
%sql select community_area_name \
     from census_data \
     where hardship_index in (select max(hardship_index) from census_data)

 * sqlite:///FinalDB.db
   sqlite:///SQLiteMagic.db
Done.

[('Riverdale',)]

In [ ]:
# Use a sub-query to determine the Community Area Name with most number of crimes?
%sql select community_area_name \
     from census_data \
     where community_area_number = (select community_area_number from chicago_crime_data \
                                    group by community_area_number \
                                    order by count(community_area_number) desc\
                                    limit 1)\
     limit 1

 * sqlite:///FinalDB.db
   sqlite:///SQLiteMagic.db
Done.

[('Austin',)]